type User @table {
  username: String!
  email: String!
  passwordHash: String!
  createdAt: Timestamp!
  displayName: String
  bio: String
  profilePictureUrl: String
  lastOnlineAt: Timestamp
}

type Connection @table(key: ["userA", "userB"]) {
  userA: User!
  userB: User!
  status: String!
  createdAt: Timestamp!
}

type Vibe @table {
  user: User!
  content: String!
  createdAt: Timestamp!
  imageUrl: String
  visibility: String
}

type Comment @table {
  user: User!
  vibe: Vibe!
  content: String!
  createdAt: Timestamp!
  parentCommentId: UUID
}

type Message @table {
  sender: User!
  receiver: User!
  content: String!
  createdAt: Timestamp!
  readAt: Timestamp
}